# Generated by Django 6.0.2 on 2026-03-02 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookhome', '0003_member_created_at_member_is_approved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bookhome.book')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bookhome.member')),
            ],
        ),
    ]
