# Generated by Django 6.0.2 on 2026-03-03 04:24

import Bookhome.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookhome', '0004_bookrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('return_date', models.DateTimeField(default=Bookhome.models.default_return_date)),
                ('returned', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bookhome.book')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bookhome.member')),
            ],
        ),
    ]
