# Generated by Django 6.0.2 on 2026-03-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookhome', '0005_issuedbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrequest',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
