# Generated by Django 6.0.2 on 2026-03-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookhome', '0006_bookrequest_returned'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuedbook',
            name='fine',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
