# Generated by Django 6.0.2 on 2026-03-06 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookhome', '0007_issuedbook_fine'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonatedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('total_copies', models.PositiveIntegerField(default=1)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Bookhome.category')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bookhome.member')),
            ],
        ),
    ]
