# Generated by Django 6.0.2 on 2026-03-12 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookhome', '0010_bookrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='donatedbook',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='donated_books/'),
        ),
    ]
